version: '3.1'
services: 
    postgres:
        image: "postgres"
        ports: 
            - '5432:5432'
        volumes: 
            - pgvol:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: test
            POSTGRES_USER: test
            POSTGRES_PASSWORD: test
        restart: unless-stopped
    pgadmin:
        image: "dpage/pgadmin4"
        depends_on:
            - postgres
        ports: 
            - "5555:80"
        environment: 
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        restart: unless-stopped
volumes: 
    pgvol: